version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - ai-service
    volumes:
      - ./backend:/backend
    networks:
      - app-network

  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "5000:5000"
    environment:
      - HF_API_TOKEN=${HF_API_TOKEN}
    volumes:
      - ./ai-service:/app
    restart: unless-stopped
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
